### ISSUE TITLE
Can't use with this SDK

### ISSUE THREAD

**Issue by KingYes** [maknz/slack#19] opened 2015-05-30 19:29 UTC
Hi..
I get this error:
```
 Catchable fatal error: Argument 1 passed to React\Promise\Promise::__construct() must be callable, null given, called in /home/yakir/slack-app/vendor/react/promise/src/Deferred.php on line 25 and defined in /home/yakir/slack-app/vendor/react/promise/src/Promise.php on line 16
```
That's the code:
```
use \Maknz\Slack\Client;

include( __DIR__ . '/vendor/autoload.php' );
$settings = [];
$client = new Client( 'my.endpoint', $settings );
$client->send( 'Test msg' );
```

**Comment by maknz** [comment] 2015-05-30 21:36
Looks like something to do with React, no? If you can trace it back to a code problem in this library I'll take a look.

**Comment by KingYes** [comment] 2015-05-30 22:11
Nope. I don't change anything.. just download from `compress`.
How I can trace it back for you?

**Comment by maknz** [comment] 2015-05-30 22:14
The stack trace you provided only mentions React, I haven't really got any reason to think there's a problem with this package.

**Comment by KingYes** [comment] 2015-05-30 22:16
How I can give you this log?

**Comment by maknz** [comment] 2015-05-30 22:18
Probably around where you got your original stack trace? Further down? Above? Does it mention an error in this package somewhere?

**Comment by KingYes** [comment] 2015-05-30 22:20
Nope. Just if I use `send()` method I get this error

**Comment by KingYes** [comment] 2015-05-30 22:29
Maybe that error cuz I run your code from WordPress?

**Comment by KingYes** [comment] 2015-05-30 22:47
I get log from the error, please give me your email to send you this file..

**Comment by maknz** [comment] 2015-05-31 00:38
Paste it here man.

**Comment by KingYes** [comment] 2015-05-31 04:51
https://gist.github.com/KingYes/979c7889795b191e7807

**Comment by maknz** [comment] 2015-05-31 05:06
Thanks for that. Looks like a problem with Guzzle or the data we're passing to Guzzle. I'll look into it and maybe get hold of the Guzzle people to see if they have any ideas. It looks like you're doing everything correctly, though.

**Comment by KingYes** [comment] 2015-05-31 05:10
Okay,
Thanks.

**Comment by maknz** [comment] 2015-05-31 05:19
Can you try specifying an older version of Guzzle to see if 5.3.0 is the problem? Try specifying "guzzlehttp/guzzle": "5.0.0" in your project's composer.json file. If that fails, try using 4.0.0.

If that works, we can fairly certainly say Guzzle is the problem, otherwise there could be an issue in how we're calling it.

**Comment by maknz** [comment] 2015-05-31 05:26
Also, I notice you made that Gist secret, but do you mind if I provide it to the Guzzle maintainers?

**Comment by KingYes** [comment] 2015-05-31 05:31
Okay, I try with `5.0.0` version and same error. But with `4.0.0` it's seem work's perfect.
And you can send this to Guzzle maintainers.

**Comment by maknz** [comment] 2015-05-31 05:40
Excellent. Change your `4.0.0` constraint to `~4.0` so you get at least the latest version of 4.x.

I've [opened an issue with Guzzle](https://github.com/guzzle/guzzle/issues/1099), hopefully they can shed some light. I'm fairly certain there must be a problem with your environment as nobody else has had any issue with Guzzle 5, but they might have seen it before.

**Comment by maknz** [comment] 2015-06-08 20:42
Closing this because the problem is isolated to your environment and isn't affecting other users, and the issue relates to Guzzle rather than this package.

**Closed by maknz** 2015-06-08 20:42 UTC
