### ISSUE TITLE
Ensure utf8

### ISSUE THREAD

**Issue by tomsommer** [maknz/slack#27] opened 2015-08-03 08:27 UTC
If non-utf8 data is provided, the json encoding fails and an Exception is thrown.

Instead the data should be converted to utf8, if non-utf8 data is provided.

**Comment by maknz** [comment] 2015-08-03 08:35
Hi there. Interesting, can you provide an example? How do you provide non utf-8 data? The code samples in the README appear to be ASCII, so I'm a bit confused here.

**Comment by tomsommer** [comment] 2015-08-03 08:44
$client->send('æøå');

If the .php document is not utf-8 encoded, then the data provided to send() is not utf8 encoded either. So a user needs to do utf8_encode() manually, something the lib should do instead, to ensure correct encoded data is sent to json_encode()

**Comment by maknz** [comment] 2015-08-03 09:00
Hmmm, cool, makes sense. I'll find some time and test this out.

**Comment by maknz** [comment] 2015-08-03 09:10
I'm actually leaning toward leaving this as is. Is there a reason you haven't got your documents encoded in UTF-8? `utf8_encode` should only be used on ISO 8859-1 strings, and this library doesn't know what encoding it will be given.

We're just doing a standard `json_encode` under the hood, nothing fancy. JSON_UNESCAPED_UNICODE is used so when we send the payload to Slack, we use proper Unicode characters, rather than \uXXX escaped chars.

**Comment by tomsommer** [comment] 2015-08-03 09:26
Yes, we have yet to convert to UTF-8, so pages are ISO 8859-1 at the moment.

At the very least the error it throws if json_encode fails is not very friendly, so some sort of check should be done to see if it fails or not.

**Comment by maknz** [comment] 2015-08-03 09:53
What is the error?

**Comment by tomsommer** [comment] 2015-08-03 09:58
exception 'InvalidArgumentException' with message 'Invalid resource type: boolean' in ..../vendor/guzzlehttp/streams/src/Stream.php:85

**Comment by maknz** [comment] 2015-08-03 10:05
I appreciate the information and PR. I'll leave this open and think about it. An exception when improperly encoded data is provided to the library is possibly a good idea.

**Comment by skyrpex** [comment] 2015-12-05 00:54
:+1: may help debugging

**Comment by Gummibeer** [comment] 2016-05-24 15:11
@maknz this issue & pr is open since more than a half year. The change is small and will fix a bug. I think that it could be merged!?
@tomsommer The only thing could be to add a unittest for this issue.

**Comment by maknz** [comment] 2016-05-27 23:30
Yep, a style fix and a test would be good. Additionally, we should make use of `json_last_error_msg` in the exception so the user knows roughly what the issue is.

**Closed** 2016-06-25 03:06 UTC
Labels: todo
